### ISSUE TITLE
shared migration pyproject.toml clarification

### ISSUE THREAD

**Issue by busla** [lucasvieirasilva/nx-plugins#174]
### Documentation issue

I am Having a hard time understanding this line.

Does this mean that there should _not_ be a `pyproject.toml` in the workspace root after the migration?
 
> After the migration is completed, the workspace does not have the pyproject.toml in the root directory, and all the local projects are referencing the root pyproject.toml file.

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://github.com/lucasvieirasilva/nx-plugins/blob/main/packages/nx-python/README.md?plain=1#L92

### Additional context or description

Provide any additional details here as needed.

**Comment by lucasvieirasilva** [comment]
@busla thanks for the feedback, this statement is wrong, it should be:

> After the migration is completed, the workspace now has a `pyproject.toml` in the root directory, and all the local projects are referencing the root `pyproject.toml` file.

Because the goal of using a shared virtual environment is to have a central `pyproject.toml` that references all the projects so you don't need to install a virtual environment per project, which takes time, compute resources, and storage.

I'm updating the docs, thanks.
